TEX_PIXELTEST  : string : #run bake_texture("C:/Users/RyDaw/Documents/jaivox/data/texture/texture_bake_test.png");
TEX_ENV_GRASS  : string : #run bake_texture("C:/Users/RyDaw/Documents/jaivox/data/texture/environment/tex_environment_grass.png");
TEX_ENV_ROCK   : string : #run bake_texture("C:/Users/RyDaw/Documents/jaivox/data/texture/environment/tex_environment_rock.png");
TEX_ENV_SAND   : string : #run bake_texture("C:/Users/RyDaw/Documents/jaivox/data/texture/environment/tex_environment_sand.png");
TEX_UNDEFINED  : string : #run bake_texture("C:/Users/RyDaw/Documents/jaivox/data/texture/tex_undef.png");
