TEX_PIXELTEST  : string : #run bake_texture("%/../data/texture/texture_bake_test.png");
TEX_ENV_GRASS  : string : #run bake_texture("%/../data/texture/environment/tex_environment_grass.png");
TEX_ENV_ROCK   : string : #run bake_texture("%/../data/texture/environment/tex_environment_rock.png");
TEX_ENV_SAND   : string : #run bake_texture("%/../data/texture/environment/tex_environment_sand.png");
TEX_UNDEFINED  : string : #run bake_texture("%/../data/texture/tex_undef.png");

TEX_ENV_GRASS_62  : string : #run bake_texture("C:/Users/RyDaw/Documents/jaivox/data/texture/environment/tex_environment_grass_big.png");

TEX_KRIS_UP    : string : #run bake_texture("%/../data/texture/tex_kris_up.png");
TEX_KRIS_DOWN  : string : #run bake_texture("%/../data/texture/tex_kris_down.png");
TEX_KRIS_LEFT  : string : #run bake_texture("%/../data/texture/tex_kris_left.png");
TEX_KRIS_RIGHT : string : #run bake_texture("%/../data/texture/tex_kris_right.png");

TEX_KRIS_BATTLE_INTRO : string : #run bake_texture("%/../data/texture/tex_kris_battle_intro.png");

//Should do a similar process for shader code files.